### ISSUE TITLE
ERROR / 414 when campaign is started

### ISSUE THREAD

**Issue by npeterson-npk** [Coalfire-Research/npk#80] opened 2020-03-02 04:16 UTC
Hi all,

I'm having an issue after I start a campaign. When I start it, the status reads "ERROR / <<number of hashes>>" - in this screenshot it was 414. https://imgur.com/a/lG1PZjO

I uploaded a wpa 4 way handshake that I know the password to, I configured the paramaters so that it would for sure have the simple 8 digit password, but it just says ERROR / 414. The stripped bar will continue to slowly fill up and eventually it will say the campaign is complete, but I can't find any sort of success indicators even though I know the password would have been tried.

Here are the errors I could find in the log: 
HTTP request sent, awaiting response... 200 OK
Length: 84579 (83K) [text/plain]
Saving to: â€˜hashes.txtâ€™

     0K .......... .......... .......... .......... .......... 60% 2.20M 0s
    50K .......... .......... .......... ..                   100% 1.47M=0.04s

2020-03-02 03:54:05 (1.84 MB/s) - â€˜hashes.txtâ€™ saved [84579/84579]

mkdir: cannot create directory â€˜npk-wordlistâ€™: File exists
fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,16 CPUs Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz (406F1),ASM,AES-NI)

Scanning the drive for archives:

Command Line Error:
Cannot find archive

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,16 CPUs Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz (406F1),ASM,AES-NI)

Scanning the drive for archives:

Command Line Error:
Cannot find archive
rm: cannot remove â€˜./npk-nullâ€™: No such file or directory

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,16 CPUs Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz (406F1),ASM,AES-NI)

Scanning the drive for archives:
1 file, 2788866 bytes (2724 KiB)

Extracting archive: hashcat.7z
--
Path = hashcat.7z
Type = 7z
Physical Size = 2788866
Headers Size = 8838
Method = LZMA2:25 LZMA:20 BCJ2
Solid = +
Blocks = 2

Everything is Ok

Folders: 41
Files: 976
Size:       27454193
Compressed: 2788866

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,16 CPUs Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz (406F1),ASM,AES-NI)

Scanning the drive for archives:
1 file, 38678 bytes (38 KiB)

Extracting archive: maskprocessor.7z
--
Path = maskprocessor.7z
Type = 7z
Physical Size = 38678
Headers Size = 360
Method = LZMA:192k BCJ
Solid = +
Blocks = 2

Everything is Ok

**Comment by npeterson-npk** [comment] 2020-03-02 18:03
I was able to find this error in my CloudWatch logs 

[ERROR] [1583165024697] LAMBDA_RUNTIME Failed to post handler success response. Http response code: 403.

**Comment by c6fc** [comment] 2020-03-26 14:58
Using the file manager, can you retrieve the manifest.json for this campaign and DM it to me?

It looks like you might have special characters in the name of your uploaded hash file that are breaking the attempt to download it from S3.

**Comment by marti2221** [comment] 2020-04-07 02:01
has this prob been solved yet? i seem to be having a similar issue (same unhandled promise rejection error)

**Comment by npeterson-npk** [comment] 2020-05-15 18:48
Hi team, so sorry I started a new job in January and COVID-19 distracted me from this project. 

I'm going to start a completely new instance and re-install tonight. Important to note: I was on a Comcast router, which I know can cause issues with random things in the past. Hoping that was the issue but I'll update here. 

I do know that "NPK-2" was talked about so I was secretly hoping it would just come out and magically solve this issue.

**Comment by marti2221** [comment] 2020-05-29 19:25
that is great news regarding the possible new version of NPK, do you have a
tentative release date yet?

**Comment by npeterson-npk** [comment] 2020-06-06 19:41
Couldn't figure out how to PM so I emailed you. Been trying everything, even just pasting 1 single PKMID in a file and uploading it. The instance starts but then I get ERROR [ / n] where n is the number of hashes I uploaded.

**Comment by HEG-IT** [comment] 2020-09-02 23:37
Having this same error, any known solution? I renamed my hash file to just hash.ntlm without success. I found these errors in the bottom of the npk log files for the instance. Looks like they're being triggered just after the hashcat options are loaded:

Credentials loaded
[ '--quiet',
  '-O',
  '--remove',
  '--potfile-path=/potfiles/i-0180149f9af50cb00.potfile',
  '-o',
  '/potfiles/cracked_hashes-i-0180149f9af50cb00.txt',
  '-w',
  '4',
  '-m',
  1000,
  '-a',
  0,
  '-r',
  '/root/npk-rules/NSAKEY.v2.dive.rule.txt',
  '-r',
  '/root/npk-rules/npk-maskprocessor.rule',
  '/root/hashes.txt',
  '/root/npk-wordlist/rockyou.txt' ]
Found status report in output
[31mnvmlDeviceGetFanSpeed(): Not Supported[0m

[31mnvmlDeviceGetFanSpeed(): Not Supported[0m

[33mHashfile '/root/hashes.txt' on line 1 (Admini...3c2ac57

**Comment by thesle3p** [comment] 2020-11-08 03:34
Can confirm this bug is still present with self hosted wordlists

**Comment by c6fc** [comment] 2020-12-05 00:32
@thesle3p do you still have your selfhost deployment? It's possible that there is a permissions issue preventing the NPK node from pulling the wordlist from your bucket. This can happen if you run the `terraform-selfhost> ./deploy.sh` and then don't run the `terraform> ./deploy.sh` afterwards. Any chance this is what you were dealing with?

**Comment by thesle3p** [comment] 2020-12-05 00:34
my instance is not currently deployed but I ran ./deploy.sh in both directories when it was up

**Comment by c6fc** [comment] 2020-12-08 05:24
> I was able to find this error in my CloudWatch logs
> 
> [ERROR] [1583165024697] LAMBDA_RUNTIME Failed to post handler success response. Http response code: 403.
> 
> Found some more:
> 2020-03-03T05:00:50.181Z 5fa78e0c-bdcf-416a-84e1-6f74b41efa68 ERROR Unhandled Promise Rejection
> {
> "errorType": "Runtime.UnhandledPromiseRejection",
> "errorMessage": "TypeError: Cannot convert undefined or null to object",
> "reason": {
> "errorType": "TypeError",
> "errorMessage": "Cannot convert undefined or null to object",
> "stack": [
> "TypeError: Cannot convert undefined or null to object",
> " at /var/task/main.js:384:5",
> " at Array.forEach ()",
> " at /var/task/main.js:354:40",
> " at processTicksAndRejections (internal/process/task_queues.js:94:5)"
> ]
> },
> "promise": {},
> "stack": [
> "Runtime.UnhandledPromiseRejection: TypeError: Cannot convert undefined or null to object",
> " at process. (/var/runtime/index.js:35:15)",
> " at process.emit (events.js:223:5)",
> " at process.EventEmitter.emit (domain.js:475:20)",
> " at processPromiseRejections (internal/process/promises.js:201:33)",
> " at processTicksAndRejections (internal/process/task_queues.js:95:32)"
> ]
> }

This is a spot_monitor error, which wouldn't effect the campaign itself. I have rewritten the spot monitor function to make it more resilient, but this error is ultimately unrelated to the issue.

**Comment by c6fc** [comment] 2020-12-08 05:25
> Having this same error, any known solution? I renamed my hash file to just hash.ntlm without success. I found these errors in the bottom of the npk log files for the instance. Looks like they're being triggered just after the hashcat options are loaded:
> 
> Credentials loaded
> [ '--quiet',
> '-O',
> '--remove',
> '--potfile-path=/potfiles/i-0180149f9af50cb00.potfile',
> '-o',
> '/potfiles/cracked_hashes-i-0180149f9af50cb00.txt',
> '-w',
> '4',
> '-m',
> 1000,
> '-a',
> 0,
> '-r',
> '/root/npk-rules/NSAKEY.v2.dive.rule.txt',
> '-r',
> '/root/npk-rules/npk-maskprocessor.rule',
> '/root/hashes.txt',
> '/root/npk-wordlist/rockyou.txt' ]
> Found status report in output
> �[31mnvmlDeviceGetFanSpeed(): Not Supported�[0m
> 
> �[31mnvmlDeviceGetFanSpeed(): Not Supported�[0m
> 
> �[33mHashfile '/root/hashes.txt' on line 1 (Admini...3c2ac57

The last line here indicates that everything else worked perfectly, but you uploaded a hash file that didn't conform with what Hashcat was expecting. Make sure you're uploading hashes in the format required for hashcat 5, and without --username as a required flag.

**Comment by c6fc** [comment] 2020-12-08 05:30
From the original post, this line is the most indicative of the actual failure:
`fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden`

This most likely indicates that after running `npk/terraform-selfhost> terraform apply` for the selfhost configuration, the OP didn't run `npk/terraform> deploy.sh` to tell the UI and Lambda functions where to find the new buckets. In this case, the hash file was retrieved correctly (from the userdata bucket, which wouldn't change with selfhost), but failed to pull the wordlist files from the dictionary buckets, which *do* change with selfhost.

I am going to close this issue. If anyone can reproduce the issue outside of the scenario listed above, feel free to create a new issue.

**Closed by c6fc** 2020-12-08 05:30 UTC
