### ISSUE TITLE
Stuck after selecting instance type

### ISSUE THREAD

**Issue by thalesredteam** [Coalfire-Research/npk#98] opened 2020-06-17 19:07 UTC
Deploying seems to go fine!
But when I select a hash file and select an intance my NPK just hangs here
![image](https://user-images.githubusercontent.com/64594526/84939351-804d4f80-b0de-11ea-92de-f35d3fd66f1f.png)
Not sure where to look for logs
Any ideas?

**Comment by thalesredteam** [comment] 2020-06-17 19:24
I also don't seem to have any dictionarys in my S3, is this normal?

**Comment by bzekanovic** [comment] 2020-06-17 20:27
I've only seen this if you setup NPK with custom domain and you are trying to access NPK via default Cloudfront domain.

**Comment by thalesredteam** [comment] 2020-06-17 20:36
Strange because I deleted those lines this is my npk-settings.json file

cat npk-settings.json
{
  "campaign_data_ttl": 604800,
  "campaign_max_price": 350,
  "georestrictions": ["DE"],
  "useCustomDNS": false,
  "route53Zone": "testZone",
  "dnsNames": {
    "www": [
    ],
    "api": [
    ]
  },
  "awsProfile": "npkcoalfire",
  "criticalEventsSMS": "xx",
  "adminEmail": "xx"
}

**Comment by thalesredteam** [comment] 2020-06-17 20:37
So I'm not even trying to use a custom domain

**Comment by thalesredteam** [comment] 2020-06-18 06:58
![image](https://user-images.githubusercontent.com/64594526/84988200-dbfcf480-b141-11ea-97eb-a427d01028fb.png)
what my browser network traffic looks like when I try to select an intance

**Comment by thalesredteam** [comment] 2020-06-18 07:02
Looks like my NPK installation gets forbidden from downloading the default wordlists and rulesets

**Comment by thalesredteam** [comment] 2020-06-18 07:19
![image](https://user-images.githubusercontent.com/64594526/84989909-ae657a80-b144-11ea-942c-fdcfea0a9416.png)
I can however reach these rules with my browser. So What's causing this to happen??

**Comment by bzekanovic** [comment] 2020-06-18 13:02
I'm not sure if leaving below empty would cause issues, but you can always check your s3 bucket CORS policy and see what its set to since that controls the authentication to your s3 bucket. At the end of the day it should be easy to tear down and configure NPK again with default settings since you are not using custom DNS. 

"www": [
],
"api": [
]

**Comment by awhitehatter** [comment] 2020-06-18 17:29
Made a change to the community buckets, try again.

**Comment by awhitehatter** [comment] 2020-06-18 19:34
Confirmed with @thalesredteam that this working now. Closing.

**Closed by awhitehatter** 2020-06-18 19:34 UTC
