### ISSUE TITLE
Error starting a campain

### ISSUE THREAD

**Issue by cyrinux** [Coalfire-Research/npk#32] opened 2019-06-26 20:49 UTC
Hi,
Thanks for the project!

I got a 502 when commiting my new campain. CloudFront return me a 502.

And i got on the interface:

Error: Unable to parse response as JSON

Any idea?

Regards

**Comment by c6fc** [comment] 2019-06-28 18:06
Closing as a duplicate of #28

**Closed by c6fc** 2019-06-28 18:06 UTC
Labels: duplicate
